version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "shop-events:1:1"
      KAFKA_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_MS: 2000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 500
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper

  kafka-admin-tool:
    image: confluentinc/cp-kafka:latest
    command: bash -c "sleep 10 && kafka-topics --alter --bootstrap-server kafka:29092 --topic shop-events --partitions 4"
    depends_on:
      - kafka
      - zookeeper
    restart: "no"

  cassandra-1:
    image: cassandra
    container_name: cassandra-1
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-1"
    ports:
      - 7000
    volumes:
      - "cassandra1:/var/lib/cassandra"
    restart: always

  cassandra-2:
    image: cassandra
    container_name: cassandra-2
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-2"
      CASSANDRA_SEEDS: "cassandra-1"
    ports:
      - 7000
    depends_on:
      - cassandra-1
    volumes:
      - "cassandra2:/var/lib/cassandra"
    restart: always

  cassandra-3:
    image: cassandra
    container_name: cassandra-3
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-3"
      CASSANDRA_SEEDS: "cassandra-1"
    ports:
      - 7000
    depends_on:
      - cassandra-2
    volumes:
      - "cassandra3:/var/lib/cassandra"
    restart: always

volumes:
  cassandra1:
    external:
      name: testvol1
  cassandra2:
    external:
      name: testvol2
  cassandra3:
    external:
      name: testvol3

networks:
  default:
    external:
      name: overlay-net